export const types = {
  login: "[Auth] Login",
  logout: "[Auth] Logout",
  uiSetError: "[UI] Set Error",
  uiRemoveError: "[UI]  Remove Error",
  uiStartLoading: "[UI] Start loading",
  uiFinishLoading: "[UI] finish loading",
  notesAddNew: "[Notes] New note",
  notesActive: "[Notes] Set actvie note",
  notesLoad: "[Notes] Load notes",
  notesUpdated: "[Notes] Updated note",
  notesFileUrl: "[Notes] Updated iamge url",
  notesDelte: "[Notes] Delete note",
  notesLogoutCleaning: "[Notes] Logout Cleaning",
};
